apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fi1at4nit-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fi1at4nit-dotnet-basic-gitops